Import("bp_ndarray_env")

tests = []

for name in ("ndarray", "ndarray_tables"):
    test_mod = bp_ndarray_env.SharedLibrary(
        "%s_mod" % name, "%s_mod.cpp" % name, SHLIBPREFIX="", LIBS=["boost_python_ndarray"]
        )
    test = bp_ndarray_env.PythonUnitTest("%s.py" % name, test_mod)
    tests.append(test)

Return("tests")
