# -*- python -*-
from lsst.sconsUtils import scripts, env

ccTests = ["ndarray.cc", "ndarray-tables.cc", "ndarray-eigen.cc"]
if env.dependencies.get("fftw"):
    ccTests.append("ndarray-fft.cc")
else:
    print "Skipping fftw interface tests."

mod = env.LoadableModuleIncomplete("ndarray_python_test", "ndarray-python-mod.cc",
                                   LIBS=env.getLibs("main python"))

ccTests, pyTests = scripts.BasicSConscript.tests(
    ccTests=ccTests,
    pyTests=["ndarray-python.py"]
)

env.Depends(pyTests, mod)
