# -*- python -*-
#
#  Copyright (c) 2010-2012, Jim Bosch
#  All rights reserved.
#
#  ndarray is distributed under a simple BSD-like license;
#  see the LICENSE file that should be present in the root
#  of the source distribution, or alternately available at:
#  https://github.com/ndarray/ndarray
#
from lsst.sconsUtils import scripts, env

ccList = ["ndarray.cc", "ndarray-eigen.cc"]
if env.dependencies.get("fftw"):
    ccList.append("ndarray-fft.cc")
else:
    print "Skipping fftw interface tests."

mod = env.SwigLoadableModule("ndarray_python_test", "ndarray-python-mod.cc",
                             LIBS=env.getLibs("main python"))

tests = scripts.BasicSConscript.tests(
    ccList=ccList,
    pyList=["ndarray-python.py"]
)

env.Depends(tests, mod)
