# -*- python -*-
from lsst.sconsUtils import scripts, env

ccList = ["ndarray.cc", "ndarray-eigen.cc"]
if env.dependencies.get("fftw"):
    ccList.append("ndarray-fft.cc")
else:
    print "Skipping fftw interface tests."

mod = env.SwigLoadableModule("ndarray_python_test", "ndarray-python-mod.cc",
                             LIBS=env.getLibs("main python"))

tests = scripts.BasicSConscript.tests(
    ccList=ccList,
    pyList=["ndarray-python.py"]
)

env.Depends(tests, mod)
