// -*- c++ -*-
/*
 * Copyright (c) 2010-2012, Jim Bosch
 * All rights reserved.
 *
 * ndarray is distributed under a simple BSD-like license;
 * see the LICENSE file that should be present in the root
 * of the source distribution, or alternately available at:
 * https://github.com/ndarray/ndarray
 */
// THIS FILE IS MACHINE GENERATED BY SCONS. DO NOT EDIT MANUALLY.
#ifndef NDARRAY_BP_AUTO_ArrayRef_h_INCLUDED
#define NDARRAY_BP_AUTO_ArrayRef_h_INCLUDED

#include "boost/numpy.hpp"
#include "ndarray/bp/ArrayRef.h"


namespace boost { namespace python {

template <typename T, int N, int C>
struct to_python_value< ndarray::ArrayRef<T,N,C> const & > : public detail::builtin_to_python {
    inline PyObject * operator()(ndarray::ArrayRef<T,N,C> const & x) const {
        object result = ndarray::ToBoostPython< ndarray::ArrayRef<T,N,C> >::apply(x);
        Py_INCREF(result.ptr());
        return result.ptr();
    }
    inline PyTypeObject const * get_pytype() const {
        return converter::object_manager_traits<
            typename ndarray::ToBoostPython< ndarray::ArrayRef<T,N,C> >::result_type
        >::get_pytype();
    }
};

template <typename T, int N, int C>
struct to_python_value< ndarray::ArrayRef<T,N,C> & > : public detail::builtin_to_python {
    inline PyObject * operator()(ndarray::ArrayRef<T,N,C> & x) const {
        object result = ndarray::ToBoostPython< ndarray::ArrayRef<T,N,C> >::apply(x);
        Py_INCREF(result.ptr());
        return result.ptr();
    }
    inline PyTypeObject const * get_pytype() const {
        return converter::object_manager_traits<
            typename ndarray::ToBoostPython< ndarray::ArrayRef<T,N,C> >::result_type
        >::get_pytype();
    }
};

namespace converter {

template <typename T, int N, int C>
struct arg_to_python< ndarray::ArrayRef<T,N,C> > : public handle<> {
    inline arg_to_python(ndarray::ArrayRef<T,N,C> const & v) :
        handle<>(to_python_value<ndarray::ArrayRef<T,N,C> const &>()(v)) {}
};

template <typename T, int N, int C>
struct arg_rvalue_from_python< ndarray::ArrayRef<T,N,C> const & > {
    typedef ndarray::ArrayRef<T,N,C> result_type;
    arg_rvalue_from_python(PyObject * p) :
        _converter(boost::python::object(boost::python::handle<>(boost::python::borrowed(p)))) {}
    bool convertible() const { return _converter.convertible(); }
    result_type operator()() const { return _converter(); }
private:
    mutable ndarray::FromBoostPython< ndarray::ArrayRef<T,N,C> > _converter;
};

template <typename T, int N, int C>
struct arg_rvalue_from_python< ndarray::ArrayRef<T,N,C> > : public arg_rvalue_from_python< ndarray::ArrayRef<T,N,C> const &> {
    arg_rvalue_from_python(PyObject * p) : arg_rvalue_from_python< ndarray::ArrayRef<T,N,C> const & >(p) {}
};

template <typename T, int N, int C>
struct arg_rvalue_from_python< ndarray::ArrayRef<T,N,C> const > : public arg_rvalue_from_python< ndarray::ArrayRef<T,N,C> const &> {
    arg_rvalue_from_python(PyObject * p) : arg_rvalue_from_python< ndarray::ArrayRef<T,N,C> const & >(p) {}
};

template <typename T, int N, int C>
struct extract_rvalue< ndarray::ArrayRef<T,N,C> > : private noncopyable {
    typedef ndarray::ArrayRef<T,N,C> result_type;
    extract_rvalue(PyObject * x) : m_converter(x) {}
    bool check() const { return m_converter.convertible(); }
    result_type operator()() const { return m_converter(); }
private:
    arg_rvalue_from_python< result_type const & > m_converter;
};

}}} // namespace boost::python::converter

#endif // !NDARRAY_BP_AUTO_ArrayRef_h_INCLUDED
