import os
Import("env")

doxy = env.Doxygen("doxygen.conf")
env.Depends(doxy, "#include/lsst/ndarray.hpp")
env.Depends(doxy, "#include/lsst/ndarray_fwd.hpp")
env.Depends(doxy, Glob("#include/lsst/ndarray/*.hpp"))
env.Depends(doxy, Glob("#include/lsst/ndarray/*/*.hpp"))
env.Depends(doxy, Glob("#m4/*.m4"))
