# -*- python -*-
#
#  Copyright (c) 2010-2012, Jim Bosch
#  All rights reserved.
#
#  ndarray is distributed under a simple BSD-like license;
#  see the LICENSE file that should be present in the root
#  of the source distribution, or alternately available at:
#  https://github.com/ndarray/ndarray
#
from lsst.sconsUtils import env

generated = ["lsst/ndarray/ArrayRef.h",
             "lsst/ndarray/operators.h",
             "lsst/ndarray/Vector.h",
             "lsst/ndarray/fft/FFTWTraits.h",
             ]
headers = [env.M4(filename, "%s.m4" % filename) for filename in generated]
