# -*- python -*-
from lsst.sconsUtils import env

generated = ["ndarray/ArrayRef.h",
             "ndarray/ArrayBaseN.h",
             "ndarray/operators.h",
             "ndarray/Vector.h",
             "ndarray/fft/FFTWTraits.h",
             ]
headers = [env.M4(filename, "%s.m4" % filename) for filename in generated]
